version: '3.1'
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 33366666622
      POSTGRES_USER: ayoung
    container_name: postgres

  springboot:
    build: .
    ports:
      - 8080:80
    depends_on:
      - postgres
