spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ars
    username: ayoung
    password: 33366666622

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true